server:
  port: 7770
  servlet:
    context-path: /
flyway:
  user: postgres
  password: 123
  schemas: essw-db
  url: jdbc:postgresql://localhost:7171/essw-db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7171/essw-db
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update





